### ISSUE TITLE
Oprava

### ISSUE THREAD

**Issue by nothumbee** [HedvikaCapkova/React1_ukol_1_barevne_palety#1]
Zadání splněno, super!

Jen doplním pár drobnost co se týče uspořádání kódu:

Ideálně bych `.map` funkce posunul o úroveň výše z komponent (tedy do App).
Protože v tu chvíli název komponenty (např. Pallete) neodpovídá realitě - tedy, že komponenta obsahuje už všechny palety a měla by se spíše jmenovat Palettes. Ale je spíše zvyklostí mít komponenty jednotného čísla.

`
{palettes.map((palette) => (
    <Palette key={palette.name} paletteData={palette}/>
))}
`

**Comment by HedvikaCapkova** [comment]
Díky za kontrolu, upravila jsem to podle tvého komentáře 🙂
